browser_flow_task:
  description: >
    Based on the PR title: "{pr_title}", PR description: "{pr_description}", 
    and repository README: "{repo_readme}", generate a concise flow description 
    for a browser AI to test the application changes.

    Include:
    - General context about the repository and its purpose
    - Step-by-step testing instructions related to the PR changes
    - Key areas to focus on during testing
    - Expected outcomes or behaviors to verify

    NEWER ask ask the browser AI to resize the window, check for responsive desing, or reload the page. ONLY simple user actions.

    Make it easy for browser AI to understand and execute.
  expected_output: >
    A clear, step-by-step flow description that a browser AI can follow to test
    the PR changes. Include repository context and specific testing steps.
  agent: browser_flow_agent

pr_comment_task:
  description: >
    Based on the PR title: "{pr_title}", PR description: "{pr_description}", 
    and repository README: "{repo_readme}", generate a helpful PR comment 
    that explains how you will test the PR.

    Use markdown formatting. Include a section for "Testing plan" with short bullet points that explains the steps you will take to test the PR.

    Always start with "# Code Turtle Review in progress"
  expected_output: >
    A nicely formatted, simple PR comment that clearly communicates the testing plan.
  agent: pr_comment_agent
